services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka-broker:
    image: confluentinc/cp-kafka:7.0.1
    restart: always
    hostname: kafka-broker
    depends_on:
      - zookeeper
    ports:
      # Map the container port 9092 to your host machine's port 9092 (for local testing/tools)
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # Advertised listeners configuration is crucial for Docker networking
      KAFKA_LISTENERS: PLAINTEXT://kafka-broker:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  postgres-db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: food_delivery_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  user-service:
    build:
      context: .
      dockerfile: Dockerfile
      target: user-service
    depends_on:
      - postgres-db
    ports:
      - "8081:8081"
    environment:
      JWT_SECRET: QyHu78l6L9ieD/yAehE+3gPzVDsGT9Mq8NQOQveQfXngZJz14dKNyAhFK3Rsiccl
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/food_delivery_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    
  restaurant-service:
    build:
      context: . 
      dockerfile: Dockerfile
      target: restaurant-service
    depends_on:
      - postgres-db
      - kafka-broker
    ports:
      - "8082:8082"
    environment:
      JWT_SECRET: QyHu78l6L9ieD/yAehE+3gPzVDsGT9Mq8NQOQveQfXngZJz14dKNyAhFK3Rsiccl
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/food_delivery_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      KAFKA_BOOTSTRAP_SERVERS: kafka-broker:9092
  
  order-service:
    build:
      context: . 
      dockerfile: Dockerfile 
      target: order-service
    depends_on:
      - postgres-db
      - kafka-broker
    ports:
      - "8083:8083"
    environment:
      JWT_SECRET: QyHu78l6L9ieD/yAehE+3gPzVDsGT9Mq8NQOQveQfXngZJz14dKNyAhFK3Rsiccl
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/food_delivery_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      KAFKA_BOOTSTRAP_SERVERS: kafka-broker:9092
  
  delivery-service:
    build:
      context: . 
      dockerfile: Dockerfile 
      target: delivery-service
    depends_on:
      - postgres-db
      - kafka-broker
    ports:
      - "8084:8084"
    environment:
      JWT_SECRET: QyHu78l6L9ieD/yAehE+3gPzVDsGT9Mq8NQOQveQfXngZJz14dKNyAhFK3Rsiccl
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/food_delivery_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      KAFKA_BOOTSTRAP_SERVERS: kafka-broker:9092

volumes:
  postgres_data:
