services:
  
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka-broker:
    image: confluentinc/cp-kafka:7.0.1
    restart: always
    hostname: kafka-broker
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # Bind both listeners on all interfaces inside the container
      KAFKA_LISTENERS: PLAINTEXT://kafka-broker:9092,PLAINTEXT_HOST://0.0.0.0:29092
      # Advertise correct addresses for each network
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  postgres-db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: food_delivery_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  user-service:
    build:
      context: .
      dockerfile: Dockerfile
      target: user-service
      args:
        - VERSION=${VERSION}
    image: minh020698/event-driven-food-delivery-user-service:${VERSION}
    depends_on:
      - postgres-db
      - service-discovery
    ports:
      - "8081:8081"
    environment:
      JWT_SECRET: QyHu78l6L9ieD/yAehE+3gPzVDsGT9Mq8NQOQveQfXngZJz14dKNyAhFK3Rsiccl
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/food_delivery_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      EUREKA_CLIENT_SERVICE_URL: http://service-discovery:8761/eureka/
    
  restaurant-service:
    build:
      context: . 
      dockerfile: Dockerfile
      target: restaurant-service
      args:
        - VERSION=${VERSION}
    image: minh020698/event-driven-food-delivery-restaurant-service:${VERSION}
    depends_on:
      - postgres-db
      - kafka-broker
      - service-discovery
    ports:
      - "8082:8082"
    environment:
      JWT_SECRET: QyHu78l6L9ieD/yAehE+3gPzVDsGT9Mq8NQOQveQfXngZJz14dKNyAhFK3Rsiccl
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/food_delivery_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      KAFKA_BOOTSTRAP_SERVERS: kafka-broker:9092
      EUREKA_CLIENT_SERVICE_URL: http://service-discovery:8761/eureka/

  order-service:
    build:
      context: . 
      dockerfile: Dockerfile 
      target: order-service
      args:
        - VERSION=${VERSION}
    image: minh020698/event-driven-food-delivery-order-service:${VERSION}
    depends_on:
      - postgres-db
      - kafka-broker
      - service-discovery
    ports:
      - "8083:8083"
    environment:
      JWT_SECRET: QyHu78l6L9ieD/yAehE+3gPzVDsGT9Mq8NQOQveQfXngZJz14dKNyAhFK3Rsiccl
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/food_delivery_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      KAFKA_BOOTSTRAP_SERVERS: kafka-broker:9092
      EUREKA_CLIENT_SERVICE_URL: http://service-discovery:8761/eureka/
  
  delivery-service:
    build:
      context: . 
      dockerfile: Dockerfile
      target: delivery-service
      args:
        VERSION: ${VERSION}
    image: minh020698/event-driven-food-delivery-delivery-service:${VERSION}
    depends_on:
      - postgres-db
      - kafka-broker
      - service-discovery
    ports:
      - "8084:8084"
    environment:
      JWT_SECRET: QyHu78l6L9ieD/yAehE+3gPzVDsGT9Mq8NQOQveQfXngZJz14dKNyAhFK3Rsiccl
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/food_delivery_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      KAFKA_BOOTSTRAP_SERVERS: kafka-broker:9092
      EUREKA_CLIENT_SERVICE_URL: http://service-discovery:8761/eureka/

  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
      target: api-gateway
      args:
        - VERSION=${VERSION}
    image: minh020698/event-driven-food-delivery-api-gateway:${VERSION}
    deploy:
      replicas: 2 # This will create two instances
    depends_on:
      - service-discovery
    networks:
      - my-app-network
    environment:
      EUREKA_CLIENT_SERVICE_URL: http://service-discovery:8761/eureka/

  service-discovery:
    build:
      context: .
      dockerfile: Dockerfile
      target: service-discovery
      args:
        - VERSION=${VERSION}
    image: minh020698/event-driven-food-delivery-service-discovery:${VERSION}
    ports:
      - "8761:8761"
    environment:
      EUREKA_CLIENT_SERVICE_URL: http://service-discovery:8761/eureka/
    networks:
      - my-app-network

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        - VITE_API_BASE_URL=/api
    image: minh020698/event-driven-food-delivery-nginx:${VERSION}
    ports:
      - "80:80"
    networks:
      - my-app-network
    # environment:
    #   VITE_API_BASE_URL: http://api-gateway:8080

volumes:
  postgres_data:

networks:
  my-app-network:
    driver: bridge
