apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-deployment
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      automountServiceAccountToken: false
      containers:
        - name: order-service
          image: minh020698/event-driven-food-delivery-order-service:0.0.1-SNAPSHOT
          ports:
            - containerPort: 8081
          resources:
            requests:
              memory: "1Gi"
              cpu: "512m"
              ephemeral-storage: "1Gi"
            limits:
              memory: "2Gi"
              cpu: "1"
          
          env:
          - name: SPRING_DATASOURCE_URL
            valueFrom:
              secretKeyRef:
                name: food-delivery-db-cluster-app
                key: jdbc-uri
          
          - name: KAFKA_BOOTSTRAP_SERVERS
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: kafka-bootstrap-servers
          
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: jwt-secret

          - name: USER_SERVICE_URL
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: user-service-url
          
          - name: RESTAURANT_SERVICE_URL
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: restaurant-service-url
          
          - name: ORDER_SERVICE_URL
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: order-service-url
          
          - name: DELIVERY_SERVICE_URL
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: delivery-service-url
          
          - name: APP_CORS_ALLOWED_ORIGINS
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: app-cors-allowed-origins


---
apiVersion: v1
kind: Service
metadata:
  name: order-service-service
spec:
  selector:
    app: order-service
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
