apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment
  namespace: ${NAMESPACE}
  labels:
    app: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      automountServiceAccountToken: false
      containers:
        - name: user-service
          image: minh020698/event-driven-food-delivery-user-service:${VERSION}
          ports:
            - containerPort: 8081
          resources:
            requests:
              memory: "1Gi"
              cpu: "256m"
              ephemeral-storage: "1Gi"
            limits:
              memory: "2Gi"
              cpu: "512m"

          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://food-delivery-db-cluster-rw.default.svc.cluster.local:5432/food_delivery_db

            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: username

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password

            - name: JWT_EXPIRATION
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: jwt-expiration

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: jwt-secret

            - name: USER_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: user-service-url

            - name: RESTAURANT_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: restaurant-service-url

            - name: ORDER_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: order-service-url

            - name: DELIVERY_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: delivery-service-url
            
            - name: APP_CORS_ALLOWED_ORIGINS
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: app-cors-allowed-origins

---
apiVersion: v1
kind: Service
metadata:
  name: user-service-service
  namespace: ${NAMESPACE}
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
